package it.polimi.ingsw.gc31.model.effects.permanent;

public enum MalusEnum {
    RESOURCEMALUS, HARVESTMALUS, PRODUCTIONMALUS, FAMILYMEMBERMALUS, CARDDICEMALUS, MARKETMALUS, SERVANTSMALUS, FIRSTACTIONMALUS, CARDPOINTSMALUS, VICTORYPOINTSMALUS, WARPOINTSMALUS, YELLOWCARDSCOSTMALUS, PLAYERRESOURCEMALUS
}
